"""Initiative workspace initializer for the staged `.b2s` engine."""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

import yaml

from b2s_engine import workspace


_BRS_TEMPLATE = """\
# Business Requirements Specification — {initiative_id}

## Metadata

| Field | Value |
|---|---|
| Initiative ID | {initiative_id} |
| Created at | {date} |
| Status | Draft |

## Objectives

| OBJ-NNN | Objective | Success Measure |
|---|---|---|
| OBJ-001 | | |

## Functional Requirements

| FR-NNN | Requirement | Business Value | Priority |
|---|---|---|---|
| FR-001 | | | |

## Non-Functional Requirements

| NFR-NNN | Requirement | Category | Measure |
|---|---|---|---|
| NFR-001 | | | |

## Constraints

| C-NNN | Constraint | Category | Source |
|---|---|---|---|
| C-001 | | | |

## Open Questions

| OQ-NNN | Question | Impact | Owner |
|---|---|---|---|
| OQ-001 | | | |
"""


_TECH_SPECS_README = """\
# Technical Specifications

This folder contains all technical specifications for this initiative.

## Structure

| Folder | Purpose | Owner |
|---|---|---|
| `api/exposed/` | OpenAPI-level specs for APIs this initiative publishes. One file per API surface. | Engineering lead |
| `api/consumed/` | Specs for external APIs this initiative depends on. One file per external system. | Engineering lead |
| `data/` | Data schemas, column definitions, constraints, migration notes. One file per domain. | Engineering lead |
| `events/` | Domain events this initiative emits and events it subscribes to. | Engineering lead |
| `integrations/` | Auth, SLA, retry policy, and fallback behaviour per external system. | Engineering lead |

## Conventions

- Each file in `api/exposed/` represents one API surface (e.g. `applications-api.md`).
- Each file in `api/consumed/` represents one external system (e.g. `experian.md`).
- Each file in `data/` represents one data domain (e.g. `applications-schema.md`).
- Each file in `integrations/` represents one external integration (e.g. `experian-integration.md`).
- Files are generated by the `create-exposed-api-specs`, `create-consumed-api-specs`,
  `create-database-schema-specs`, and `create-integration-specs` workflow actions.
"""

_TECH_SPECS_LEAF_DIRS = [
    "api/exposed",
    "api/consumed",
    "data",
    "events",
    "integrations",
]


def _create_technical_specs_layout(workspace_root: Path) -> None:
    """Create the canonical technical-specifications folder tree with tracking files."""
    tech_root = workspace.technical_specs_root(workspace_root)
    for leaf in _TECH_SPECS_LEAF_DIRS:
        leaf_dir = tech_root / leaf
        leaf_dir.mkdir(parents=True, exist_ok=True)
        (leaf_dir / ".gitkeep").write_text("", encoding="utf-8")
    (tech_root / "README.md").write_text(_TECH_SPECS_README, encoding="utf-8")


def _copy_workflow_type(workspace_root: Path, workflow_type: str) -> None:
    """Copy workflow type files into the initiative workspace."""
    index_path = workspace.FRAMEWORK_ROOT / "workflow-types" / "index.yaml"
    if not index_path.exists():
        raise FileNotFoundError(
            f"Workflow types index not found: {index_path}\n"
            "Run the framework setup to create it."
        )

    index = yaml.safe_load(index_path.read_text(encoding="utf-8"))
    types_by_id = {wt["id"]: wt for wt in index.get("workflow_types", [])}

    if workflow_type not in types_by_id:
        available = ", ".join(types_by_id.keys())
        raise ValueError(
            f"Unknown workflow type: '{workflow_type}'. "
            f"Available types: {available}"
        )

    source_dir = workspace.REPO_ROOT / types_by_id[workflow_type]["path"]
    dest_dir = workspace_root / ".b2s" / "workflow"
    dest_dir.mkdir(parents=True, exist_ok=True)

    for filename in ("stage-actions.yaml", "workflow-definition.yaml"):
        source = source_dir / filename
        dest = dest_dir / filename
        if not source.exists():
            raise FileNotFoundError(
                f"Workflow type '{workflow_type}' is missing {filename}: {source}"
            )
        shutil.copyfile(source, dest)

    record = {
        "workflow_type": workflow_type,
        "source_path": str(source_dir),
        "copied_at": datetime.now(tz=timezone.utc).isoformat(),
        "files_copied": ["stage-actions.yaml", "workflow-definition.yaml"],
    }
    workspace.save_json_file(dest_dir / "workflow-type.json", record)


def run(args: object) -> None:
    initiative_id = getattr(args, "initiative_id", None)
    workspace_root_arg = getattr(args, "workspace_root", None)

    # Derive workspace root from initiative_id if not explicitly passed
    if workspace_root_arg is not None:
        workspace_root = workspace_root_arg.resolve()
    elif initiative_id is not None:
        initiatives_dir = workspace.FRAMEWORK_ROOT.parent / "initiatives"
        workspace_root = initiatives_dir / initiative_id
    else:
        raise ValueError("Provide --initiative-id or --workspace-root.")

    if workspace_root.exists():
        raise FileExistsError(
            f"Workspace already exists: {workspace_root}\n"
            "Use reset-to-phase to restart an existing initiative."
        )

    # Infer initiative_id from the folder name if only workspace_root was given
    if initiative_id is None:
        initiative_id = workspace_root.name

    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    # --- Create folder structure ---
    input_dir = workspace_root / "input"
    input_dir.mkdir(parents=True)

    # --- Create technical-specifications tree ---
    _create_technical_specs_layout(workspace_root)

    # --- Seed input/brs.md ---
    brs_path = input_dir / "brs.md"
    brs_path.write_text(
        _BRS_TEMPLATE.format(initiative_id=initiative_id, date=today),
        encoding="utf-8",
    )

    # --- Seed .b2s runtime layout (state + tmp) ---
    workspace.ensure_runtime_layout(workspace_root)

    # --- Copy selected workflow type into the initiative ---
    workflow_type = getattr(args, "workflow_type", None) or "enterprise-modular"
    _copy_workflow_type(workspace_root, workflow_type)

    # --- Write initiative_id and workflow_type into workflow-state.json ---
    state = workspace.load_state(workspace_root)
    state["initiative_id"] = initiative_id
    state["workflow_type"] = workflow_type
    state["state_validated"] = True
    state["last_updated"] = datetime.now(tz=timezone.utc).isoformat()
    workspace.save_state(workspace_root, state)

    # --- Report ---
    result = {
        "overall": "pass",
        "initiative_id": initiative_id,
        "workspace_root": str(workspace_root),
        "workflow_type": workflow_type,
        "workflow_files": [
            ".b2s/workflow/stage-actions.yaml",
            ".b2s/workflow/workflow-definition.yaml",
            ".b2s/workflow/workflow-type.json",
        ],
        "created": [
            str(brs_path.relative_to(workspace_root)),
            ".b2s/state/workflow-state.json",
            ".b2s/state/open-decisions.md",
            ".b2s/workflow/stage-actions.yaml",
            ".b2s/workflow/workflow-definition.yaml",
            ".b2s/workflow/workflow-type.json",
            "technical-specifications/README.md",
            *[f"technical-specifications/{d}/.gitkeep" for d in _TECH_SPECS_LEAF_DIRS],
        ],
        "next_action": "route-initiative",
        "message": (
            f"Initiative {initiative_id} workspace created with workflow type '{workflow_type}'. "
            f"Fill in {brs_path.relative_to(workspace_root)} then run the workflow."
        ),
    }

    output_path = workspace_root / ".b2s" / "tmp" / "init-workspace.json"
    if getattr(args, "output", None) is not None:
        output_arg = args.output
        output_path = (
            output_arg.resolve()
            if output_arg.is_absolute()
            else (workspace_root / output_arg).resolve()
        )

    workspace.save_json_file(output_path, result)
    workspace.append_execution_log(
        workspace_root,
        command="init-workspace",
        overall=result["overall"],
        details={
            "created": result["created"],
            "message": result["message"],
        },
    )
    print(json.dumps(result, indent=2))
